### ISSUE TITLE
On click or hover show the featured image

### ISSUE THREAD

**Issue by bacloud14** [bacloud14/SunnySunday#12]
I created a separate card that would contain (or not) a thumbnail of the featured image. On click or on hover should show the featured picture which should be hidden by default.

**Comment by aditya28sarin** [comment]
Can you assign this issue to me?

**Comment by bacloud14** [comment]
Sure Aditya, thanks for passing by. As my policy in this repo, feel free to add an attribution to you, (github..) in footer. When everything works fine. 
Did you get the website to work by the way ? with your keys set ?

**Comment by bacloud14** [comment]
Hello @aditya28sarin 
any follow up for this ? 
thanks 👍

**Comment by bacloud14** [comment]
no longer need. changed to an album.
